export const SELECT_MONTH = 'SELECT_NEW_MONTH';
export const SELECT_YEAR = 'SELECT_YEAR';
export const SELECT_DAY = 'SELECT_DAY';

export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const MODIFY_TASK__CONTENT = 'MODIFY_TASK__CONTENT';
export const MODIFY_TASK__COMPLETE = 'MODIFY_TASK__COMPLETE';
export const FETCH_NEW_TASKS = 'FETCH_NEW_TASKS';
export const RECEIVE_NEW_TASKS = 'RECEIVE_NEW_TASKS';
export const SEND_NEW_TASKS = 'SEND_NEW_TASKS';
export const SAVED_NEW_TASKS = 'SAVED_NEW_TASKS';