export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const MODIFY_TASK__CONTENT = 'MODIFY_TASK__CONTENT';
export const MODIFY_TASK__COMPLETE = 'MODIFY_TASK__COMPLETE';
export const FETCH_NEW_TASKS = 'FETCH_NEW_TASKS';
export const RECEIVE_NEW_TASKS = 'RECEIVE_NEW_TASKS';
export const COMMIT_LIST_CHANGES = 'COMMIT_LIST_CHANGES';
export const COMMITTED_SUCCESSFULLY = 'COMMITTED_SUCCESSFULLY';